name: Code Check

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

     steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Check Kotlin code
      run: |
        curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.41.0/ktlint && chmod +x ktlint
        ./ktlint --version
        ./ktlint --color src/**/*.kt

    - name: Check XML code
      run: |
        sudo apt-get install libxml2-utils
        xmllint --noout --schema path/to/schema.xsd src/**/*.xml

    - name: Check Gradle files
      run: |
        ./gradlew check
